//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BugTrackLikeModel", "FK_T_Bug_T_Project", "T_Project", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SyndicationServiceBugTrack.DataAccess.T_Project), "T_Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SyndicationServiceBugTrack.DataAccess.T_Bug), true)]
[assembly: EdmRelationshipAttribute("BugTrackLikeModel", "FK_T_Comment_T_Bug", "T_Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SyndicationServiceBugTrack.DataAccess.T_Bug), "T_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SyndicationServiceBugTrack.DataAccess.T_Comment), true)]
[assembly: EdmRelationshipAttribute("BugTrackLikeModel", "FK_T_Transaction_T_Bug", "T_Bug", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SyndicationServiceBugTrack.DataAccess.T_Bug), "T_Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SyndicationServiceBugTrack.DataAccess.T_Transaction), true)]
[assembly: EdmRelationshipAttribute("BugTrackLikeModel", "FK_T_Comment_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SyndicationServiceBugTrack.DataAccess.T_User), "T_Comment", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SyndicationServiceBugTrack.DataAccess.T_Comment), true)]
[assembly: EdmRelationshipAttribute("BugTrackLikeModel", "FK_T_Transaction_T_User", "T_User", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SyndicationServiceBugTrack.DataAccess.T_User), "T_Transaction", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SyndicationServiceBugTrack.DataAccess.T_Transaction), true)]

#endregion

namespace SyndicationServiceBugTrack.DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BugTrackLikeEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BugTrackLikeEntities object using the connection string found in the 'BugTrackLikeEntities' section of the application configuration file.
        /// </summary>
        public BugTrackLikeEntities() : base("name=BugTrackLikeEntities", "BugTrackLikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackLikeEntities object.
        /// </summary>
        public BugTrackLikeEntities(string connectionString) : base(connectionString, "BugTrackLikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BugTrackLikeEntities object.
        /// </summary>
        public BugTrackLikeEntities(EntityConnection connection) : base(connection, "BugTrackLikeEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Bug> T_Bug
        {
            get
            {
                if ((_T_Bug == null))
                {
                    _T_Bug = base.CreateObjectSet<T_Bug>("T_Bug");
                }
                return _T_Bug;
            }
        }
        private ObjectSet<T_Bug> _T_Bug;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Comment> T_Comment
        {
            get
            {
                if ((_T_Comment == null))
                {
                    _T_Comment = base.CreateObjectSet<T_Comment>("T_Comment");
                }
                return _T_Comment;
            }
        }
        private ObjectSet<T_Comment> _T_Comment;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Project> T_Project
        {
            get
            {
                if ((_T_Project == null))
                {
                    _T_Project = base.CreateObjectSet<T_Project>("T_Project");
                }
                return _T_Project;
            }
        }
        private ObjectSet<T_Project> _T_Project;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_Transaction> T_Transaction
        {
            get
            {
                if ((_T_Transaction == null))
                {
                    _T_Transaction = base.CreateObjectSet<T_Transaction>("T_Transaction");
                }
                return _T_Transaction;
            }
        }
        private ObjectSet<T_Transaction> _T_Transaction;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<T_User> T_User
        {
            get
            {
                if ((_T_User == null))
                {
                    _T_User = base.CreateObjectSet<T_User>("T_User");
                }
                return _T_User;
            }
        }
        private ObjectSet<T_User> _T_User;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Bug EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Bug(T_Bug t_Bug)
        {
            base.AddObject("T_Bug", t_Bug);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Comment EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Comment(T_Comment t_Comment)
        {
            base.AddObject("T_Comment", t_Comment);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Project EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Project(T_Project t_Project)
        {
            base.AddObject("T_Project", t_Project);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_Transaction EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_Transaction(T_Transaction t_Transaction)
        {
            base.AddObject("T_Transaction", t_Transaction);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the T_User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToT_User(T_User t_User)
        {
            base.AddObject("T_User", t_User);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackLikeModel", Name="T_Bug")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Bug : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Bug object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="title">Initial value of the title property.</param>
        /// <param name="idProjet">Initial value of the idProjet property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        /// <param name="createdate">Initial value of the Createdate property.</param>
        public static T_Bug CreateT_Bug(global::System.Int64 id, global::System.String title, global::System.Int64 idProjet, global::System.String type, global::System.String description, global::System.DateTime createdate)
        {
            T_Bug t_Bug = new T_Bug();
            t_Bug.id = id;
            t_Bug.title = title;
            t_Bug.idProjet = idProjet;
            t_Bug.Type = type;
            t_Bug.Description = description;
            t_Bug.Createdate = createdate;
            return t_Bug;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String title
        {
            get
            {
                return _title;
            }
            set
            {
                OntitleChanging(value);
                ReportPropertyChanging("title");
                _title = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("title");
                OntitleChanged();
            }
        }
        private global::System.String _title;
        partial void OntitleChanging(global::System.String value);
        partial void OntitleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idProjet
        {
            get
            {
                return _idProjet;
            }
            set
            {
                OnidProjetChanging(value);
                ReportPropertyChanging("idProjet");
                _idProjet = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idProjet");
                OnidProjetChanged();
            }
        }
        private global::System.Int64 _idProjet;
        partial void OnidProjetChanging(global::System.Int64 value);
        partial void OnidProjetChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Createdate
        {
            get
            {
                return _Createdate;
            }
            set
            {
                OnCreatedateChanging(value);
                ReportPropertyChanging("Createdate");
                _Createdate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Createdate");
                OnCreatedateChanged();
            }
        }
        private global::System.DateTime _Createdate;
        partial void OnCreatedateChanging(global::System.DateTime value);
        partial void OnCreatedateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Bug_T_Project", "T_Project")]
        public T_Project T_Project
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Project>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Project").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Project>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Project").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Project> T_ProjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Project>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Project");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Project>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Project", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Comment_T_Bug", "T_Comment")]
        public EntityCollection<T_Comment> T_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Comment>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Comment>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Transaction_T_Bug", "T_Transaction")]
        public EntityCollection<T_Transaction> T_Transaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Transaction>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Transaction>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Transaction", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackLikeModel", Name="T_Comment")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Comment : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Comment object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idUser">Initial value of the idUser property.</param>
        /// <param name="idBug">Initial value of the idBug property.</param>
        /// <param name="details">Initial value of the details property.</param>
        public static T_Comment CreateT_Comment(global::System.Int64 id, global::System.Int64 idUser, global::System.Int64 idBug, global::System.String details)
        {
            T_Comment t_Comment = new T_Comment();
            t_Comment.id = id;
            t_Comment.idUser = idUser;
            t_Comment.idBug = idBug;
            t_Comment.details = details;
            return t_Comment;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                OnidUserChanging(value);
                ReportPropertyChanging("idUser");
                _idUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idUser");
                OnidUserChanged();
            }
        }
        private global::System.Int64 _idUser;
        partial void OnidUserChanging(global::System.Int64 value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idBug
        {
            get
            {
                return _idBug;
            }
            set
            {
                OnidBugChanging(value);
                ReportPropertyChanging("idBug");
                _idBug = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idBug");
                OnidBugChanged();
            }
        }
        private global::System.Int64 _idBug;
        partial void OnidBugChanging(global::System.Int64 value);
        partial void OnidBugChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String details
        {
            get
            {
                return _details;
            }
            set
            {
                OndetailsChanging(value);
                ReportPropertyChanging("details");
                _details = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("details");
                OndetailsChanged();
            }
        }
        private global::System.String _details;
        partial void OndetailsChanging(global::System.String value);
        partial void OndetailsChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Comment_T_Bug", "T_Bug")]
        public T_Bug T_Bug
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Bug").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Bug").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Bug> T_BugReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Comment_T_Bug", "T_Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Comment_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Comment_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Comment_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Comment_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("BugTrackLikeModel.FK_T_Comment_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackLikeModel", Name="T_Project")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Project : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Project object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="version">Initial value of the version property.</param>
        /// <param name="startDate">Initial value of the startDate property.</param>
        public static T_Project CreateT_Project(global::System.Int64 id, global::System.String name, global::System.Double version, global::System.DateTime startDate)
        {
            T_Project t_Project = new T_Project();
            t_Project.Id = id;
            t_Project.name = name;
            t_Project.version = version;
            t_Project.startDate = startDate;
            return t_Project;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private global::System.Double _version;
        partial void OnversionChanging(global::System.Double value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime startDate
        {
            get
            {
                return _startDate;
            }
            set
            {
                OnstartDateChanging(value);
                ReportPropertyChanging("startDate");
                _startDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("startDate");
                OnstartDateChanged();
            }
        }
        private global::System.DateTime _startDate;
        partial void OnstartDateChanging(global::System.DateTime value);
        partial void OnstartDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Bug_T_Project", "T_Bug")]
        public EntityCollection<T_Bug> T_Bug
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Bug>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Bug>("BugTrackLikeModel.FK_T_Bug_T_Project", "T_Bug", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackLikeModel", Name="T_Transaction")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_Transaction : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_Transaction object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="idBug">Initial value of the idBug property.</param>
        /// <param name="idUser">Initial value of the idUser property.</param>
        /// <param name="statut">Initial value of the statut property.</param>
        public static T_Transaction CreateT_Transaction(global::System.Int64 id, global::System.Int64 idBug, global::System.Int64 idUser, global::System.String statut)
        {
            T_Transaction t_Transaction = new T_Transaction();
            t_Transaction.id = id;
            t_Transaction.idBug = idBug;
            t_Transaction.idUser = idUser;
            t_Transaction.statut = statut;
            return t_Transaction;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idBug
        {
            get
            {
                return _idBug;
            }
            set
            {
                OnidBugChanging(value);
                ReportPropertyChanging("idBug");
                _idBug = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idBug");
                OnidBugChanged();
            }
        }
        private global::System.Int64 _idBug;
        partial void OnidBugChanging(global::System.Int64 value);
        partial void OnidBugChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 idUser
        {
            get
            {
                return _idUser;
            }
            set
            {
                OnidUserChanging(value);
                ReportPropertyChanging("idUser");
                _idUser = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idUser");
                OnidUserChanged();
            }
        }
        private global::System.Int64 _idUser;
        partial void OnidUserChanging(global::System.Int64 value);
        partial void OnidUserChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String statut
        {
            get
            {
                return _statut;
            }
            set
            {
                OnstatutChanging(value);
                ReportPropertyChanging("statut");
                _statut = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("statut");
                OnstatutChanged();
            }
        }
        private global::System.String _statut;
        partial void OnstatutChanging(global::System.String value);
        partial void OnstatutChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Transaction_T_Bug", "T_Bug")]
        public T_Bug T_Bug
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Bug").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Bug").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_Bug> T_BugReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Bug");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_Bug>("BugTrackLikeModel.FK_T_Transaction_T_Bug", "T_Bug", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Transaction_T_User", "T_User")]
        public T_User T_User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_User").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_User").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<T_User> T_UserReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<T_User>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<T_User>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_User", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BugTrackLikeModel", Name="T_User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class T_User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new T_User object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="firstname">Initial value of the firstname property.</param>
        /// <param name="email">Initial value of the email property.</param>
        /// <param name="phone">Initial value of the phone property.</param>
        /// <param name="password">Initial value of the password property.</param>
        public static T_User CreateT_User(global::System.Int64 id, global::System.String name, global::System.String firstname, global::System.String email, global::System.String phone, global::System.String password)
        {
            T_User t_User = new T_User();
            t_User.id = id;
            t_User.name = name;
            t_User.firstname = firstname;
            t_User.email = email;
            t_User.phone = phone;
            t_User.password = password;
            return t_User;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String firstname
        {
            get
            {
                return _firstname;
            }
            set
            {
                OnfirstnameChanging(value);
                ReportPropertyChanging("firstname");
                _firstname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("firstname");
                OnfirstnameChanged();
            }
        }
        private global::System.String _firstname;
        partial void OnfirstnameChanging(global::System.String value);
        partial void OnfirstnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Comment_T_User", "T_Comment")]
        public EntityCollection<T_Comment> T_Comment
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Comment>("BugTrackLikeModel.FK_T_Comment_T_User", "T_Comment");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Comment>("BugTrackLikeModel.FK_T_Comment_T_User", "T_Comment", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BugTrackLikeModel", "FK_T_Transaction_T_User", "T_Transaction")]
        public EntityCollection<T_Transaction> T_Transaction
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<T_Transaction>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_Transaction");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<T_Transaction>("BugTrackLikeModel.FK_T_Transaction_T_User", "T_Transaction", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
