//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientBugTrack.ServiceReferenceBugTrack {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BugTransfert", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DBO")]
    [System.SerializableAttribute()]
    public partial class BugTransfert : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProjectNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResponsableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProjectName {
            get {
                return this.ProjectNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProjectNameField, value) != true)) {
                    this.ProjectNameField = value;
                    this.RaisePropertyChanged("ProjectName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Responsable {
            get {
                return this.ResponsableField;
            }
            set {
                if ((object.ReferenceEquals(this.ResponsableField, value) != true)) {
                    this.ResponsableField = value;
                    this.RaisePropertyChanged("Responsable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Bug", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_BugCritic))]
    public partial class T_Bug : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment[] T_Bug_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Project T_ProjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_ProjectCp_S5ox3a T_ProjectReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Transaction[] T_TransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateDate {
            get {
                return this.CreateDateField;
            }
            set {
                if ((this.CreateDateField.Equals(value) != true)) {
                    this.CreateDateField = value;
                    this.RaisePropertyChanged("CreateDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment[] T_Bug_Comment {
            get {
                return this.T_Bug_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.T_Bug_CommentField, value) != true)) {
                    this.T_Bug_CommentField = value;
                    this.RaisePropertyChanged("T_Bug_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Project T_Project {
            get {
                return this.T_ProjectField;
            }
            set {
                if ((object.ReferenceEquals(this.T_ProjectField, value) != true)) {
                    this.T_ProjectField = value;
                    this.RaisePropertyChanged("T_Project");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_ProjectCp_S5ox3a T_ProjectReference {
            get {
                return this.T_ProjectReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_ProjectReferenceField, value) != true)) {
                    this.T_ProjectReferenceField = value;
                    this.RaisePropertyChanged("T_ProjectReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Transaction[] T_Transaction {
            get {
                return this.T_TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.T_TransactionField, value) != true)) {
                    this.T_TransactionField = value;
                    this.RaisePropertyChanged("T_Transaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Transaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_BugCritic))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Transaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_BugCritic))]
    public partial class EntityObject : ClientBugTrack.ServiceReferenceBugTrack.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Bug_Comment", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_Bug_Comment : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Bug T_BugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a T_BugReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Comment T_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_CommentCp_S5ox3a T_CommentReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug T_Bug {
            get {
                return this.T_BugField;
            }
            set {
                if ((object.ReferenceEquals(this.T_BugField, value) != true)) {
                    this.T_BugField = value;
                    this.RaisePropertyChanged("T_Bug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a T_BugReference {
            get {
                return this.T_BugReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_BugReferenceField, value) != true)) {
                    this.T_BugReferenceField = value;
                    this.RaisePropertyChanged("T_BugReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Comment T_Comment {
            get {
                return this.T_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CommentField, value) != true)) {
                    this.T_CommentField = value;
                    this.RaisePropertyChanged("T_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_CommentCp_S5ox3a T_CommentReference {
            get {
                return this.T_CommentReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CommentReferenceField, value) != true)) {
                    this.T_CommentReferenceField = value;
                    this.RaisePropertyChanged("T_CommentReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Comment", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_Comment : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment[] T_Bug_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_User T_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a T_UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string detailsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idBugField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment[] T_Bug_Comment {
            get {
                return this.T_Bug_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.T_Bug_CommentField, value) != true)) {
                    this.T_Bug_CommentField = value;
                    this.RaisePropertyChanged("T_Bug_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_User T_User {
            get {
                return this.T_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserField, value) != true)) {
                    this.T_UserField = value;
                    this.RaisePropertyChanged("T_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a T_UserReference {
            get {
                return this.T_UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserReferenceField, value) != true)) {
                    this.T_UserReferenceField = value;
                    this.RaisePropertyChanged("T_UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string details {
            get {
                return this.detailsField;
            }
            set {
                if ((object.ReferenceEquals(this.detailsField, value) != true)) {
                    this.detailsField = value;
                    this.RaisePropertyChanged("details");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idBug {
            get {
                return this.idBugField;
            }
            set {
                if ((this.idBugField.Equals(value) != true)) {
                    this.idBugField = value;
                    this.RaisePropertyChanged("idBug");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_User", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_User : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Comment[] T_CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Transaction[] T_TransactionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Comment[] T_Comment {
            get {
                return this.T_CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.T_CommentField, value) != true)) {
                    this.T_CommentField = value;
                    this.RaisePropertyChanged("T_Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Transaction[] T_Transaction {
            get {
                return this.T_TransactionField;
            }
            set {
                if ((object.ReferenceEquals(this.T_TransactionField, value) != true)) {
                    this.T_TransactionField = value;
                    this.RaisePropertyChanged("T_Transaction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstname {
            get {
                return this.firstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstnameField, value) != true)) {
                    this.firstnameField = value;
                    this.RaisePropertyChanged("firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Transaction", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_Transaction : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Bug T_BugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a T_BugReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_User T_UserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a T_UserReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int statutField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug T_Bug {
            get {
                return this.T_BugField;
            }
            set {
                if ((object.ReferenceEquals(this.T_BugField, value) != true)) {
                    this.T_BugField = value;
                    this.RaisePropertyChanged("T_Bug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a T_BugReference {
            get {
                return this.T_BugReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_BugReferenceField, value) != true)) {
                    this.T_BugReferenceField = value;
                    this.RaisePropertyChanged("T_BugReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_User T_User {
            get {
                return this.T_UserField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserField, value) != true)) {
                    this.T_UserField = value;
                    this.RaisePropertyChanged("T_User");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a T_UserReference {
            get {
                return this.T_UserReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.T_UserReferenceField, value) != true)) {
                    this.T_UserReferenceField = value;
                    this.RaisePropertyChanged("T_UserReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int statut {
            get {
                return this.statutField;
            }
            set {
                if ((this.statutField.Equals(value) != true)) {
                    this.statutField = value;
                    this.RaisePropertyChanged("statut");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_Project", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_Project : ClientBugTrack.ServiceReferenceBugTrack.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.T_Bug[] T_BugField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string versionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug[] T_Bug {
            get {
                return this.T_BugField;
            }
            set {
                if ((object.ReferenceEquals(this.T_BugField, value) != true)) {
                    this.T_BugField = value;
                    this.RaisePropertyChanged("T_Bug");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                if ((object.ReferenceEquals(this.versionField, value) != true)) {
                    this.versionField = value;
                    this.RaisePropertyChanged("version");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="T_BugCritic", Namespace="http://schemas.datacontract.org/2004/07/lemett_aBugTrack.DataAccess", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class T_BugCritic : ClientBugTrack.ServiceReferenceBugTrack.T_Bug {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfT_ProjectCp_S5ox3a", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfT_ProjectCp_S5ox3a : ClientBugTrack.ServiceReferenceBugTrack.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityKeyMember[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_CommentCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_ProjectCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Bug_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Comment))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_User))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Comment[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Transaction[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Transaction))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_Project))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.T_BugCritic))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.BugTransfert[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.BugTransfert))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfT_BugCp_S5ox3a", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfT_BugCp_S5ox3a : ClientBugTrack.ServiceReferenceBugTrack.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_CommentCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_ProjectCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a))]
    public partial class EntityReference : ClientBugTrack.ServiceReferenceBugTrack.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientBugTrack.ServiceReferenceBugTrack.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientBugTrack.ServiceReferenceBugTrack.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_UserCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_CommentCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_ProjectCp_S5ox3a))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ClientBugTrack.ServiceReferenceBugTrack.EntityReferenceOfT_BugCp_S5ox3a))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfT_UserCp_S5ox3a", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfT_UserCp_S5ox3a : ClientBugTrack.ServiceReferenceBugTrack.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfT_CommentCp_S5ox3a", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfT_CommentCp_S5ox3a : ClientBugTrack.ServiceReferenceBugTrack.EntityReference {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBugTrack.IServiceClientBugTrack")]
    public interface IServiceClientBugTrack {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientBugTrack/GetListBug", ReplyAction="http://tempuri.org/IServiceClientBugTrack/GetListBugResponse")]
        ClientBugTrack.ServiceReferenceBugTrack.BugTransfert[] GetListBug(int max);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceClientBugTrack/GetListBugWithEF", ReplyAction="http://tempuri.org/IServiceClientBugTrack/GetListBugWithEFResponse")]
        ClientBugTrack.ServiceReferenceBugTrack.T_Bug[] GetListBugWithEF(int max);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceClientBugTrackChannel : ClientBugTrack.ServiceReferenceBugTrack.IServiceClientBugTrack, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClientBugTrackClient : System.ServiceModel.ClientBase<ClientBugTrack.ServiceReferenceBugTrack.IServiceClientBugTrack>, ClientBugTrack.ServiceReferenceBugTrack.IServiceClientBugTrack {
        
        public ServiceClientBugTrackClient() {
        }
        
        public ServiceClientBugTrackClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClientBugTrackClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientBugTrackClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClientBugTrackClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientBugTrack.ServiceReferenceBugTrack.BugTransfert[] GetListBug(int max) {
            return base.Channel.GetListBug(max);
        }
        
        public ClientBugTrack.ServiceReferenceBugTrack.T_Bug[] GetListBugWithEF(int max) {
            return base.Channel.GetListBugWithEF(max);
        }
    }
}
